version: "3.8"

services:
  ui: 
    container_name: xts-ui-test
    tty: true
    image: xts-ui-test
    build:
      context: ./frontend
      target: production
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
