version: "3.8"

services:
  ui: 
    container_name: xts-ui-test
    tty: true
    image: xts-ui-test
    build:
      context: ./frontend
      target: test
    ports: 
      - 3000:3000
    volumes:
      - ./frontend/src:/www/src
    networks:
      - xts-app-network
  api:
    platform: linux/x86_64
    container_name: xts-api-test
    environment:
      - DOCKER_BUILDKIT=0
      - COMPOSE_DOCKER_CLI_BUILD=0
      - SPRING_PROFILES_ACTIVE=test
    tty: true
    image: xts-api-test
    build:
      context: ./backend
    ports:
      - 8080:8080
    networks:
      - xts-app-network
  nginx:
    container_name: xts-nginx-test
    tty: true
    image: xts-nginx-test
    build:
      context: ./nginx
    ports: 
      - 80:80
    networks:
      - xts-app-network
  storage:
    container_name: storage
    tty: true
    image: xts-storage
    build:
      context: ./storage
    volumes:
      - ./storage/images:/www/images
    ports:
      - 8081:80
    networks:
      - xts-app-network

networks:
  xts-app-network:
    driver: bridge