version: "3.8"

services:
  ui: 
    container_name: xts-ui
    tty: true
    image: xts-ui
    build:
      target: production
      context: ./frontend
    ports: 
      - 3000:3000
    volumes:
      - ./frontend/src:/www/src
    networks:
      - xts-app-network
  api:
    platform: linux/x86_64
    container_name: xts-api
    environment:
      - DOCKER_BUILDKIT=0
      - COMPOSE_DOCKER_CLI_BUILD=0
    tty: true
    image: xts-api
    build:
      context: ./backend
    ports:
      - 8080:8080
    networks:
      - xts-app-network
  nginx:
    container_name: xts-nginx
    tty: true
    image: xts-nginx
    build:
      context: ./ngnix
    ports: 
      - 80:80
    networks:
      - bridge
      - xts-app-network
      
  # db:
  #   container_name: xts-db
  #   tty: true
  #   image: 'postgres:13'
  #   ports: 
  #     - 5432:5432
  #   volumes:
  #     - xts-dbdata:/var/lib/postgresql/data
  #   networks:
  #     - xts-db-network

networks:
  xts-app-network:
    driver: bridge

# volumes:
#   xts-dbdata:
#     drive: local