version: "3.8"

services:
  api:
    platform: linux/x86_64
    container_name: xts-api-test
    environment:
      - DOCKER_BUILDKIT=0
      - COMPOSE_DOCKER_CLI_BUILD=0
      - SPRING_PROFILES_ACTIVE=test
    tty: true
    image: xts-api-test
    build:
      context: ./backend
    ports:
      - 8080:8080
    networks:
      - xts-app-network
  nginx:
    container_name: xts-nginx-test
    tty: true
    image: xts-nginx-test
    build:
      context: ./nginx
      target: test
    ports: 
      - 80:80
    networks:
      - xts-app-network

networks:
  xts-app-network:
    driver: bridge